version: '3'
services:
    # web:
    #     image: nginx:alpine
    #     volumes:
    #         - "./etc/nginx/default.conf:/etc/nginx/conf.d/default.conf"
    #         - "${METINFO_PATH}:/var/www/html"
    #         - "./etc/nginx/default.template.conf:/etc/nginx/conf.d/default.template"
    #     ports:
    #         - "8000:80"
    #     environment:
    #         - NGINX_HOST=${NGINX_HOST}
    #     command: /bin/sh -c "envsubst '$$NGINX_HOST' < /etc/nginx/conf.d/default.template > /etc/nginx/conf.d/default.conf && nginx -g 'daemon off;'"
    #     restart: always
    #     depends_on:
    #         - php
    php:
        image: nanoninja/php-fpm:${PHP_VERSION}
        restart: always
        ports:
            - "9000:9000"
        volumes:
            - "./etc/php/php.ini:/usr/local/etc/php/conf.d/php.ini"
            - "${METINFO_PATH}:/var/www/web"
            - "${WEBPAGE_PATH}:/var/www/webpage"
        extra_hosts:
            - "${WEB_DOMAIN}:${WEB_IP}" # 做一个域名映射，